# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [5]:
A = np.arange(1, 16).reshape(3,5)

In [4]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

2
(3, 5)
15
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [5]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [6]:
print('Elementwise subtraction (B-C):')
print(B-C)
print('Elementwise multiplication (B*C):')
print(B*C)
print('Matrix multiplication:')
print(B@C)  # <-- can also use B.dot(C)

Elementwise subtraction (B-C):
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
Elementwise multiplication (B*C):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
Matrix multiplication:
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [7]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print(np.exp(B))
print(B.min())
print(B.min(axis=1))
print(B.min(axis=0))
print(np.argmin(B))
print(np.argmin(B,axis=1))
print(np.sum(B))
print(np.mean(B, axis=0))
print(np.median(B, axis=0))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 4 7]
[1 2 3]
0
[0 0 0]
45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [9]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [10]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

It fills out with colons to match the number of axes (treats the remaining axes as full slices)

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [11]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [41]:
for i in A.ravel(): # <-- can also use flatten()
    print(i)

# A less efficiant way but still works:
# for i in A:
#     for j in i:
#         print(j)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [42]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


Creates an array from 0 to 29 and changes the shape from 1 dimension to 3 dimensions.
it specifies the size of 2 of the dimensions and lets numpy figure out the last dimension to fit with all the vaules.
The result becomes a 2x3x5 array.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [43]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [44]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [48]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)
print()
print(A.shape == b.shape)
print()
print(A + b)

[[1 2]
 [3 4]]
[2 2]

False

[[3 4]
 [5 6]]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [13]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [14]:
def do_stuff_with_matrices(m1: np.ndarray, m2: np.ndarray, operation: str):
    """Can either add or multiply two matrices. 
    It takes matrices as the first two arguments and the oprator you want to use as the last (add or multiply)
    """

    if isinstance(m1, np.ndarray) and isinstance(m2, np.ndarray):
        if operation not in ('add', 'subtract', 'multiply'):
            raise Exception('Operation can only be "add", "subtract" or "multiply".')

        elif operation == 'add':
            if m1.shape == m2.shape:
                answer = m1 + m2
                return answer
            else:
                print('The matrices are not the same shape!')
            
        elif operation == 'subtract': # <-- Technically not nessisary since we can use add
            if m1.shape == m2.shape:
                answer = m1 - m2
                return answer
            else:
                print('The matrices are not the same shape!')
    
        elif operation == 'multiply':
            if m1.shape[1] == m2.shape[0]:
                answer = m1@m2
                return answer
            else:
                print('The first matrix columns do not match the second matrix rows')
    else:
        raise TypeError('The first two arguments need to be of type np.ndarray.')


print('B-2A:')
print(do_stuff_with_matrices(B, A*2, 'subtract'))
print('3C-E:')
print(do_stuff_with_matrices(C*3, E, 'subtract'))
print('AC:')
print(do_stuff_with_matrices(A, C, 'multiply'))
print('CD:')
print(do_stuff_with_matrices(C, D, 'multiply'))
print('CB:')
print(do_stuff_with_matrices(C, B, 'multiply'))

B-2A:
[[ 0 -4  3]
 [ 0 -2 -4]]
3C-E:
The matrices are not the same shape!
None
AC:
The first matrix columns do not match the second matrix rows
None
CD:
[[11 10]
 [10 11]]
CB:
[[  8 -10  -3]
 [ 10  -8   0]]


**Chap2. Question 2**

In [16]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

AB = do_stuff_with_matrices(A, B, 'multiply')
AC = do_stuff_with_matrices(A, C, 'multiply')
print(AB)
print()
print(AC)
print()
print('AB=AC:', (AB == AC).all())
print()
print('B=C:', (B == C).all())

[[ 4  7]
 [ 8 14]]

[[ 4  7]
 [ 8 14]]

AB=AC: True

B=C: False


**Chap2. Question 3**

In [17]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

print('AD:\n', do_stuff_with_matrices(A, D, 'multiply'))
print()
print('DA:\n', do_stuff_with_matrices(D, A, 'multiply'))

AD:
 [[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]

DA:
 [[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [116]:
A = np.array([[1, -1], [-1, 1]])
B = np.array([[-1, 1], [1, -1]])
print(do_stuff_with_matrices(A, B, 'multiply'))

[[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [21]:
A = np.array([[5, 6], [4, 5]])
B = np.array([[6, 4], [3, 3]])

# NumPy has an inbuilt function numpy.linalg.inv that does this with all square matrices
# but here I made one myself

def matrix_inverse(matrix: np.ndarray):
    """Takes the inverse of the 2x2-matrix given."""

    a = matrix[0][0]
    b = matrix[0][1]
    c = matrix[1][0]
    d = matrix[1][1]
    switch_array = np.array([[d, -b], [-c, a]])
    inverse = (1/(a*d-b*c))*switch_array
    return inverse

print('Inverse of A:\n', matrix_inverse(A))
# Checking to see if A @ A^-1 is the Identity matrix
print('A @ A^-1=I:\n', np.allclose(A @ matrix_inverse(A), np.eye(2))) # <-- np.allclose compares if two arrays are the same within some toleranceses
print()
print('Inverse of B:\n', matrix_inverse(B))
print('B @ B^-1=I:\n', np.allclose(B @ matrix_inverse(B), np.eye(2)))

Inverse of A:
 [[ 5. -6.]
 [-4.  5.]]
A @ A^-1=I:
 True

Inverse of B:
 [[ 0.5        -0.66666667]
 [-0.5         1.        ]]
B @ B^-1=I:
 True


**Quiz p.19, Question 3**

In [124]:
A = np.array([[2, 2], [1, 2]])

print(matrix_inverse(A))

[[ 1.  -1. ]
 [-0.5  1. ]]


**Chap10. Question 1 a)**

In [23]:
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
b = np.array([[-7], [5], [2]])
print('x:\n', np.linalg.solve(A, b))

print('Ax=b:\n', np.allclose(A @ np.linalg.solve(A, b), b))

x:
 [[ 3.]
 [ 4.]
 [-6.]]
Ax=b:
 True


**Chap10. Question 1 b)**

In [24]:
A = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
B = np.array([[1], [-1], [1]])
print(np.linalg.solve(A, B))

print('Ax=B:\n', np.allclose(A @ np.linalg.solve(A, B), B))

[[ 8.]
 [ 2.]
 [-1.]]
Ax=B:
 True


**Chap 12. Question 1**

In [25]:
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
print(np.linalg.inv(A))

print('A @ A^-1 = I:\n', np.allclose(A @ np.linalg.inv(A), np.eye(3)))

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]
A @ A^-1 = I:
 True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [129]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [130]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [131]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
